name: mir-kiosk-x11-example
version: '0.1'
summary: example (zoom) X11 kiosk, using mir_kiosk_x11
description: |
  example (zoom) X11 kiosk, using mir_kiosk_x11
base: core20
confinement: strict
grade: devel

apps:
  mir-kiosk-x11-example:
#    daemon: simple
#    restart-condition: always
    command-chain:
      - env-setup
    command: usr/local/bin/x11_kiosk_launch $SNAP/usr/bin/zoom

architectures:
  - amd64

parts:
  zoom:
    plugin: dump
    source: https://zoom.us/client/latest/zoom_amd64.deb
    override-build: |
      rm -f $SNAPCRAFT_PART_BUILD/usr/bin/zoom
      echo "QT_QPA_PLATFORM=xcb LD_LIBRARY_PATH=\$SNAP/opt/zoom:\$LD_LIBRARY_PATH \$SNAP/opt/zoom/ZoomLauncher" > $SNAPCRAFT_PART_BUILD/usr/bin/zoom
      chmod +x $SNAPCRAFT_PART_BUILD/usr/bin/zoom
      sed -i s/D_LIBRAR/XXXXXXXX/g opt/zoom/ZoomLauncher
      snapcraftctl build
    stage-packages:
      - libnspr4
      - libnss3
      - libpulse-mainloop-glib0
      - libqt53dcore5
      - libqt53dinput5
      - libqt53dlogic5
      - libqt53dquick5
      - libqt53dquickscene2d5
      - libqt53drender5
      - libqt5concurrent5
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libqt5network5
      - libqt5printsupport5
      - libqt5qml5
      - libqt5quick5
      - libqt5quickcontrols2-5
      - libqt5quickparticles5
      - libqt5quicktemplates2-5
      - libqt5sql5
      - libqt5waylandclient5
      - libqt5widgets5
      - libqt5xmlpatterns5
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-xtest0
      - libx11-6
      - libxtst6
      - pulseaudio-utils
      - libqt5gamepad5
      - libxi6
      - libatk1.0-0
      - libcairo-gobject2
      - libcairo2
      - libgtk-3-0
      - libgdk-pixbuf2.0-0
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpulse0

  # The rest is "boiler plate" to set up an X11 environment for the application
  ppa-setup:
    plugin: nil
    override-pull: |
      sudo apt --assume-yes install software-properties-common
      sudo add-apt-repository -y ppa:mir-team/release
      sudo apt install --assume-yes libmiral-dev
      snapcraftctl pull

  mir-kiosk-x11:
    after: [ppa-setup]
    plugin: cmake
    source: https://github.com/MirServer/mir_kiosk_x11.git
    build-packages:
      - pkg-config
      - libmiral-dev
      - make
      - g++
    stage-packages:
      - inotify-tools
      - libmiral4
      - mir-platform-graphics-wayland18
      - dmz-cursor-theme
      - fonts-freefont-ttf
      - xwayland
      - libbz2-1.0

  env-setup:
    plugin: dump
    source: env-setup

layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts

plugs:
  opengl:         # For Mir
  wayland:        # For Mir
  network-bind:   # For Mir (to serve X11)
  camera:         # For Zoom
  audio-playback: # For Zoom
  audio-record:   # For Zoom

environment:
  # Prep for Mir
  MIR_SERVER_PLATFORM_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/mir/server-platform
  MIR_SERVER_XWAYLAND_PATH: ${SNAP}/usr/bin/Xwayland
  # GL setup
  __EGL_VENDOR_LIBRARY_DIRS: $SNAP/etc/glvnd/egl_vendor.d:$SNAP/usr/share/glvnd/egl_vendor.d
  LIBGL_DRIVERS_PATH: $SNAP/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri
  LD_LIBRARY_PATH: ${SNAP}/usr/lib/${SNAPCRAFT_ARCH_TRIPLET}:${SNAP}/lib/${SNAPCRAFT_ARCH_TRIPLET}
