name: mir-kiosk-x11-example     # YOUR SNAP NAME GOES HERE
version: '0.1'                  # YOUR SNAP VERSION GOES HERE
summary: example X11 kiosk      # YOUR SUMMARY GOES HERE
description: example X11 kiosk  # YOUR DESCRIPTION GOES HERE
base: core20
confinement: strict
grade: devel

apps:
  mir-kiosk-x11-example:
#    daemon: simple
#    restart-condition: always
    command-chain:
      - env-setup
    command: usr/local/bin/x11_kiosk_launch ### YOUR COMMAND GOES HERE

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

parts:
  ### YOUR PART GOES HERE
  your-part:
    plugin: nil
    stage-snaps:
      - mir-kiosk-x11/latest/edge

# Needed by Mir and/or Xwayland
layout:
  /usr/share/X11:
    bind: $SNAP/usr/share/X11
  /usr/bin/xkbcomp:
    symlink: $SNAP/usr/bin/xkbcomp
  /usr/share/icons:
    bind: $SNAP/usr/share/icons
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts
  /etc/fonts:
    bind: $SNAP/etc/fonts

plugs:
  opengl:         # For Mir
  wayland:        # For Mir
  network-bind:   # For Mir (to serve X11)
